In [1]:
import pandas as pd

In [2]:
df_vac_mopac = pd.read_csv("results/vacuum_results.csv")
df_sol_mopac = pd.read_csv("results/water_results.csv")
df_mlp = pd.read_csv("results.csv")

In [3]:
df_vac_mopac

                              file status  heat_of_formation  total_energy
0  conf_01_water_opt_vacuum_sp.out     ok         -109.74715           NaN
1  conf_02_water_opt_vacuum_sp.out     ok         -109.21043           NaN
2  conf_03_water_opt_vacuum_sp.out     ok         -108.50741           NaN
3  conf_04_water_opt_vacuum_sp.out     ok         -109.51650           NaN
4  conf_05_water_opt_vacuum_sp.out     ok         -109.38009           NaN
5  conf_06_water_opt_vacuum_sp.out     ok         -108.10518           NaN
6  conf_07_water_opt_vacuum_sp.out     ok         -107.32544           NaN
7  conf_08_water_opt_vacuum_sp.out     ok         -109.69169           NaN
8  conf_09_water_opt_vacuum_sp.out     ok         -108.94605           NaN
9  conf_10_water_opt_vacuum_sp.out     ok         -109.92187           NaN

In [4]:
df_sol_mopac

                    file status  heat_of_formation  total_energy
0  conf_01_water_opt.out     ok         -161.52987           NaN
1  conf_02_water_opt.out     ok         -161.41128           NaN
2  conf_03_water_opt.out     ok         -161.70021           NaN
3  conf_04_water_opt.out     ok         -161.43526           NaN
4  conf_05_water_opt.out     ok         -161.85241           NaN
5  conf_06_water_opt.out     ok         -161.46098           NaN
6  conf_07_water_opt.out     ok         -160.66058           NaN
7  conf_08_water_opt.out     ok         -161.23754           NaN
8  conf_09_water_opt.out     ok         -160.62342           NaN
9  conf_10_water_opt.out     ok         -161.69359           NaN

In [6]:
df_mlp

,sdf_path,molecule_index,conformer_index,ml_model,n_rotatable_torsions,restraint_force_constant_kcal_per_mol_rad2,minimisation_max_iterations,openmm_platform,minimised_sdf_path,energy_kcal_per_mol_excluding_restraints
0,/home/campus.ncl.ac.uk/c2033567/Documents/3QTU...,0,0,mace-off23-medium,6,100000.0,0,CUDA,NaN,-4814.089704
1,/home/campus.ncl.ac.uk/c2033567/Documents/3QTU...,0,0,mace-off23-medium,6,100000.0,0,CUDA,NaN,-4815.200756

In [7]:
# mopac_vac_07 = df_vac_mopac.iloc[6, df_vac_mopac.columns.get_loc("heat_of_formation")]
mopac_vac_07 = df_vac_mopac.loc[6, "heat_of_formation"]
mopac_vac_07 = float(mopac_vac_07)
type(mopac_vac_07)

float

In [8]:
mopac_sol_07 = df_sol_mopac.loc[6, "heat_of_formation"]
mopac_sol_07 = float(mopac_sol_07)

In [10]:
mlp_vac_07 = df_mlp.loc[0, "energy_kcal_per_mol_excluding_restraints"]
mlp_vac_07 = float(mlp_vac_07)

In [11]:
mlp_sol_07 = df_mlp.loc[1, "energy_kcal_per_mol_excluding_restraints"]
mlp_sol_07 = float(mlp_sol_07)

In [14]:
dhyd_mlp = mlp_sol_07 - mlp_vac_07
print(f"{dhyd_mlp} kcal/mol")

-1.1110518314026194 kcal/mol

In [16]:
dhyd_mopac = mopac_sol_07 - mopac_vac_07
print(f"{dhyd_mopac} kcal/mol")

-53.33514000000001 kcal/mol

In [17]:
dg_lig = dhyd_mlp + dhyd_mopac
print(f"{dg_lig} kcal/mol")

-54.44619183140263 kcal/mol